- pkg:composer/styleci/config@v0.1.0-alpha
- pkg:composer/styleci/config@v0.2.0-alpha
- pkg:composer/styleci/config@v0.3.0-alpha
- pkg:composer/styleci/config@v0.3.1-alpha
- pkg:composer/styleci/config@v0.3.2-alpha
- pkg:composer/styleci/config@v0.3.3-alpha
- pkg:composer/styleci/config@v0.4.0-alpha
- pkg:composer/styleci/config@v1.0.0
- pkg:composer/styleci/config@v2.0.0
- pkg:composer/styleci/config@v2.1.0
- pkg:composer/styleci/config@v2.10.0
- pkg:composer/styleci/config@v2.11.0
- pkg:composer/styleci/config@v2.2.0
- pkg:composer/styleci/config@v2.3.0
- pkg:composer/styleci/config@v2.4.0
- pkg:composer/styleci/config@v2.5.0
- pkg:composer/styleci/config@v2.6.0
- pkg:composer/styleci/config@v2.7.0
- pkg:composer/styleci/config@v2.8.0
- pkg:composer/styleci/config@v2.9.0
