- pkg:composer/sirs/tasks@1.0.0
- pkg:composer/sirs/tasks@1.0.1
- pkg:composer/sirs/tasks@1.0.2
- pkg:composer/sirs/tasks@1.3.0
- pkg:composer/sirs/tasks@10.0.0
- pkg:composer/sirs/tasks@11.0
- pkg:composer/sirs/tasks@11.0.1
- pkg:composer/sirs/tasks@11.0.2
- pkg:composer/sirs/tasks@12.0
- pkg:composer/sirs/tasks@2.0.0
- pkg:composer/sirs/tasks@2.0.1
- pkg:composer/sirs/tasks@2.0.10
- pkg:composer/sirs/tasks@2.0.11
- pkg:composer/sirs/tasks@2.0.12
- pkg:composer/sirs/tasks@2.0.2
- pkg:composer/sirs/tasks@2.0.3
- pkg:composer/sirs/tasks@2.0.4
- pkg:composer/sirs/tasks@2.0.5
- pkg:composer/sirs/tasks@2.0.6
- pkg:composer/sirs/tasks@2.0.7
- pkg:composer/sirs/tasks@2.0.8
- pkg:composer/sirs/tasks@2.0.9
- pkg:composer/sirs/tasks@2.1.0
- pkg:composer/sirs/tasks@2.1.1
- pkg:composer/sirs/tasks@2.1.2
- pkg:composer/sirs/tasks@2.1.3
- pkg:composer/sirs/tasks@2.1.4
- pkg:composer/sirs/tasks@2.2.0
- pkg:composer/sirs/tasks@2.2.1
- pkg:composer/sirs/tasks@2.3.0
- pkg:composer/sirs/tasks@2.3.1
- pkg:composer/sirs/tasks@2.3.10
- pkg:composer/sirs/tasks@2.3.11
- pkg:composer/sirs/tasks@2.3.12
- pkg:composer/sirs/tasks@2.3.2
- pkg:composer/sirs/tasks@2.3.3
- pkg:composer/sirs/tasks@2.3.4
- pkg:composer/sirs/tasks@2.3.5
- pkg:composer/sirs/tasks@2.3.6
- pkg:composer/sirs/tasks@2.3.7
- pkg:composer/sirs/tasks@2.3.8
- pkg:composer/sirs/tasks@2.3.9
- pkg:composer/sirs/tasks@2.4.0
- pkg:composer/sirs/tasks@2.4.1
- pkg:composer/sirs/tasks@2.4.10
- pkg:composer/sirs/tasks@2.4.11
- pkg:composer/sirs/tasks@2.4.13
- pkg:composer/sirs/tasks@2.4.14
- pkg:composer/sirs/tasks@2.4.15
- pkg:composer/sirs/tasks@2.4.16
- pkg:composer/sirs/tasks@2.4.17
- pkg:composer/sirs/tasks@2.4.18
- pkg:composer/sirs/tasks@2.4.19
- pkg:composer/sirs/tasks@2.4.2
- pkg:composer/sirs/tasks@2.4.20
- pkg:composer/sirs/tasks@2.4.21
- pkg:composer/sirs/tasks@2.4.3
- pkg:composer/sirs/tasks@2.4.4
- pkg:composer/sirs/tasks@2.4.5
- pkg:composer/sirs/tasks@2.4.6
- pkg:composer/sirs/tasks@2.4.7
- pkg:composer/sirs/tasks@2.4.8
- pkg:composer/sirs/tasks@2.4.9
- pkg:composer/sirs/tasks@3.0.0
- pkg:composer/sirs/tasks@3.0.1
- pkg:composer/sirs/tasks@3.0.10
- pkg:composer/sirs/tasks@3.0.11
- pkg:composer/sirs/tasks@3.0.2
- pkg:composer/sirs/tasks@3.0.3
- pkg:composer/sirs/tasks@3.0.4
- pkg:composer/sirs/tasks@3.0.5
- pkg:composer/sirs/tasks@3.0.6
- pkg:composer/sirs/tasks@3.0.7
- pkg:composer/sirs/tasks@3.0.8
- pkg:composer/sirs/tasks@3.0.9
- pkg:composer/sirs/tasks@4.0.0
- pkg:composer/sirs/tasks@4.0.1
- pkg:composer/sirs/tasks@4.0.10
- pkg:composer/sirs/tasks@4.0.11
- pkg:composer/sirs/tasks@4.0.12
- pkg:composer/sirs/tasks@4.0.2
- pkg:composer/sirs/tasks@4.0.3
- pkg:composer/sirs/tasks@4.0.4
- pkg:composer/sirs/tasks@4.0.5
- pkg:composer/sirs/tasks@4.0.6
- pkg:composer/sirs/tasks@4.0.7
- pkg:composer/sirs/tasks@4.0.8
- pkg:composer/sirs/tasks@4.0.9
- pkg:composer/sirs/tasks@9.0.0
