- pkg:composer/werx/config@0.0.1
- pkg:composer/werx/config@0.1.0
- pkg:composer/werx/config@0.2.0
- pkg:composer/werx/config@0.3.0
- pkg:composer/werx/config@1.0
- pkg:composer/werx/config@1.0.1
- pkg:composer/werx/config@1.1.0
- pkg:composer/werx/config@1.2.0
- pkg:composer/werx/config@1.3
